tasks:
  - name: pulumi
    before: |
      curl -fsSL https://get.pulumi.com | sh
  - name: cdk
    before: |
      sh ./bin/npm_aws_cdk_install.sh
  - name: terraform-cli
    before: |
      sh ./bin/terraform_cli_install.sh
  - name: utils
    before: |
      sudo apt-get install tree
  - name: powershell
    before: |
      sh ./bin/powershell_cli_install.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      sh ./bin/aws_cli_install.sh